# DROP TABLES

songplay_table_drop = "DROP TABLE IF EXISTS SONGPLAY;"
user_table_drop = "DROP TABLE IF EXISTS USERS;"
song_table_drop = "DROP TABLE IF EXISTS SONGS;"
artist_table_drop = "DROP TABLE IF EXISTS ARTISTS;"
time_table_drop = "DROP TABLE IF EXISTS TIME;"

# CREATE TABLES

songplay_table_create = ("""CREATE TABLE IF NOT EXISTS SONGPLAY(
SONGPLAY_ID SERIAL, START_TIME BIGINT NOT NULL, USER_ID INT NOT NULL,LEVEL VARCHAR, SONG_ID VARCHAR, ARTIST_ID VARCHAR, SESSION_ID INT, LOCATION VARCHAR, USER_AGENT VARCHAR, PRIMARY KEY (SONGPLAY_ID));
""")

user_table_create = ("""CREATE TABLE IF NOT EXISTS USERS(
USER_ID INT, FIRST_NAME VARCHAR, LAST_NAME VARCHAR, GENDER VARCHAR(1), LEVEL VARCHAR, PRIMARY KEY(USER_ID));
""")

song_table_create = ("""CREATE TABLE IF NOT EXISTS SONGS(SONG_ID VARCHAR, TITLE VARCHAR, ARTIST_ID VARCHAR,
YEAR INT, DURATION FLOAT, PRIMARY KEY(SONG_ID));
""")

artist_table_create = ("""CREATE TABLE IF NOT EXISTS ARTISTS(
ARTIST_ID VARCHAR, NAME VARCHAR, LOCATION VARCHAR, LATITUDE DECIMAL, LONGITUDE DECIMAL, PRIMARY KEY(ARTIST_ID));
""")

time_table_create = ("""CREATE TABLE IF NOT EXISTS TIME(
START_TIME TIMESTAMP, HOUR INT, DAY INT, WEEK INT, MONTH INT, YEAR INT, WEEKDAY INT, PRIMARY KEY(START_TIME));
""")

# INSERT RECORDS

songplay_table_insert = ("""INSERT INTO SONGPLAY(START_TIME, USER_ID, LEVEL, SONG_ID, ARTIST_ID, SESSION_ID, LOCATION, USER_AGENT) VALUES (%s,%s,%s,%s,%s,%s,%s,%s);
""")

user_table_insert = ("""INSERT INTO USERS(USER_ID, FIRST_NAME, LAST_NAME, GENDER, LEVEL) VALUES (%s,%s,%s,%s,%s)
ON CONFLICT (USER_ID) DO UPDATE SET LEVEL=EXCLUDED.LEVEL;
""")

song_table_insert = """INSERT INTO SONGS(SONG_ID, TITLE, ARTIST_ID, YEAR, DURATION) VALUES (%s,%s,%s,%s,%s)
ON CONFLICT (SONG_ID) DO NOTHING;
"""

artist_table_insert = ("""INSERT INTO ARTISTS(ARTIST_ID, LATITUDE, LOCATION, LONGITUDE, NAME) VALUES (%s,%s,%s,%s,%s)
ON CONFLICT (ARTIST_ID) DO NOTHING;
""")

time_table_insert = ("""INSERT INTO TIME(START_TIME, HOUR, DAY, WEEK, MONTH, YEAR, WEEKDAY) VALUES (%s,%s,%s,%s,%s,%s,%s)
ON CONFLICT (START_TIME) DO NOTHING;
""")

# FIND SONGS

song_select = ("""SELECT  S.SONG_ID, S.ARTIST_ID FROM (SONGS S JOIN ARTISTS A ON S.ARTIST_ID = A.ARTIST_ID)
                     WHERE S.TITLE = %s AND A.NAME = %s AND S.DURATION = %s""")

# QUERY LISTS

create_table_queries = [songplay_table_create, user_table_create, song_table_create, artist_table_create, time_table_create]
drop_table_queries = [songplay_table_drop, user_table_drop, song_table_drop, artist_table_drop, time_table_drop]